-- the idea is as follows:
-- t1: ∀ point a b, suppose there's a path r a b, then it is always possible to find a path s a b, if the last
-- segment of r a b is in r1
-- main theorem:
-- by contradiction given the loop on r x x
-- simply do a case analysis on the last segment of r and first segment of r
